apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv5g
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  mountOptions:
    - nfsvers=4.1
    - hard
  nfs:
    path: /
    server: fs-0123456789abcdef0.efs.us-east-1.amazonaws.com   # your EFS ID and region